version: "2.0"
services:
  mysql-servicee:
    image: mysql:5.7
    container_name: mysql-servicee
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome123
  fmr-service:
    image: sayanta/find-my-room-service:latest
    container_name: fmr-service
    restart: on-failure
    ports:
      - "8089:8080"
    depends_on:
      - mysql-servicee
  fmr-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - fmr-service
