version: "2.0"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome123
  web-service:
    image: sayanta/find-my-room-service:latest
    container_name: web-service
    restart: on-failure
    ports:
      - "8089:8080"
    depends_on:
      - mysql
  ui-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - web-service

