# Define 'Service' to expose FrontEnd Application
apiVersion: v1
kind: Service
metadata:
  name: fmr-frontend
spec:
  selector: # pod labels should match these
    app: fmr
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 32018
  type: NodePort # use NodePort if you are not running Kubernetes on Cloud
---
# 'Deployment' to manage of configuration of frontEnd Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fmr-frontend
  labels: # pod labels should match these
    app: fmr
    tier: frontend
spec:
  replicas: 2  # number of replicas of frontEnd application
  selector:
    matchLabels: 
      app: fmr
      tier: frontend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: fmr
        tier: frontend  
    spec:                 
      containers: 
      - name: fmr-frontend 
        image: mahesh2210/findmyroomui:kube # docker image of frontend application
        env: # Setting Environmental Variables
          -  name: SERVER_URI # Setting Backend URI from configMap
             value: "http://poc-docker.eastus.cloudapp.azure.com:32304"
        ports:
        - containerPort: 8080